In [22]:
from transformers import AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [23]:
raw_inputs = [
    "I enjory my intership time in BOPRC.",
    "I like it so much!",
]
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="tf")
print(inputs)

{'input_ids': <tf.Tensor: shape=(2, 14), dtype=int32, numpy=
array([[  101,  1045,  4372,  5558,  2854,  2026,  6970,  9650,  2051,
         1999, 29432, 11890,  1012,   102],
       [  101,  1045,  2066,  2009,  2061,  2172,   999,   102,     0,
            0,     0,     0,     0,     0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 14), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]], dtype=int32)>}


In [24]:
from transformers import TFAutoModel

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFAutoModel.from_pretrained(checkpoint)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFDistilBertModel: ['classifier.bias', 'pre_classifier.weight', 'classifier.weight', 'pre_classifier.bias']
- This IS expected if you are initializing TFDistilBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFDistilBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [25]:
outputs = model(inputs)
print(outputs.last_hidden_state.shape)

(2, 14, 768)


In [26]:
from transformers import TFAutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(inputs)

All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [27]:
print(outputs.logits.shape)

(2, 2)


In [28]:
print(outputs.logits)

tf.Tensor(
[[-2.3977735  2.54413  ]
 [-4.356724   4.7141857]], shape=(2, 2), dtype=float32)


The [-1.5606999  1.6122847] for first sentence, [ 4.169231  -3.346447 ] for second sentence.
They are logits, he raw, unnormalized scores outputted by the last layer of the model. 

In [29]:
import tensorflow as tf

predictions = tf.math.softmax(outputs.logits, axis=-1)
# print(predictions)

# transfer the value in predictions to show as float with 4 decimal places
predictions = tf.math.softmax(outputs.logits, axis=-1).numpy().tolist()
for i, prediction in enumerate(predictions):
    print(f"{i}: {prediction}")


0: [0.007090360391885042, 0.9929096698760986]
1: [0.00011494868522277102, 0.999885082244873]


In [30]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}